import { describe, it, expect, beforeEach, vi } from 'vitest'

// Regression test for the double-generation bug: a week that already has
// session_inventory must NOT be regenerated by generateWeekInventory unless the
// caller explicitly forces it. Prior to the guard, a double-dispatch of the
// wizard/lazy path stacked a second AI pool onto the same week (~2x sessions).

const { genPool, currentCount } = vi.hoisted(() => ({
    genPool: vi.fn(async () => ({ success: false as const, error: 'stop-after-guard' })),
    currentCount: { value: 0 },
}))

vi.mock('next/cache', () => ({ revalidatePath: vi.fn() }))

// generateSessionPool is the expensive AI call the guard must skip.
vi.mock('@/lib/engine/microcycle/generate-pool', () => ({
    generateSessionPool: genPool,
}))

// Allocation helpers — no-ops for this test.
vi.mock('../inventory.actions', () => ({
    suggestAllocation: vi.fn(async () => ({ success: false, error: 'n/a' })),
    applyAllocation: vi.fn(async () => ({ success: false, error: 'n/a' })),
}))

vi.mock('@/lib/supabase/server', () => {
    const buildChain = (table: string): any => {
        const chain: any = {
            select: vi.fn(() => chain),
            eq: vi.fn(() => chain),
            in: vi.fn(() => chain),
            order: vi.fn(() => chain),
            limit: vi.fn(() => chain),
            insert: vi.fn(() => chain),
            delete: vi.fn(() => chain),
            single: vi.fn(async () => {
                if (table === 'microcycles') {
                    return { data: { id: 'micro-1', week_number: 2, mesocycle_id: 'meso-1' }, error: null }
                }
                return { data: null, error: null }
            }),
            maybeSingle: vi.fn(async () => ({ data: null, error: null })),
            // Thenable terminal — resolves the count query / list reads.
            then: (resolve: any) => {
                if (table === 'session_inventory') {
                    return resolve({ data: null, count: currentCount.value, error: null })
                }
                if (table === 'workouts') {
                    return resolve({ data: [], error: null })
                }
                if (table === 'microcycles') {
                    // Grid read by rebaseMicrocyclesFromWeek. Week 2 starts today,
                    // so the rebase is a no-op and this test stays focused on the
                    // idempotency guard.
                    const today = new Date().toISOString().split('T')[0]
                    const plus = (d: number) =>
                        new Date(Date.parse(today) + d * 86_400_000).toISOString().split('T')[0]
                    return resolve({
                        data: [
                            { id: 'micro-0', week_number: 1, start_date: plus(-7), end_date: plus(-1) },
                            { id: 'micro-1', week_number: 2, start_date: today, end_date: plus(6) },
                        ],
                        error: null,
                    })
                }
                return resolve({ data: null, error: null })
            },
        }
        return chain
    }

    const client = {
        from: vi.fn((table: string) => buildChain(table)),
        auth: { getUser: vi.fn().mockResolvedValue({ data: { user: { id: 'u1' } }, error: null }) },
    }
    return { createClient: vi.fn(async () => client) }
})

import { generateWeekInventory } from '../inventory-generation.actions'

describe('generateWeekInventory idempotency guard', () => {
    beforeEach(() => {
        genPool.mockClear()
        currentCount.value = 0
    })

    it('no-ops (does not regenerate) when the week already has inventory', async () => {
        currentCount.value = 8

        const result = await generateWeekInventory('micro-1')

        expect(result.success).toBe(true)
        if (result.success) {
            expect(result.data.sessions).toBe(8)
            expect(result.data.weekNumber).toBe(2)
            expect(result.data.mesocycleId).toBe('meso-1')
        }
        // The expensive AI generation must never run for an already-populated week.
        expect(genPool).not.toHaveBeenCalled()
    })

    it('bypasses the guard when force:true (regeneration path)', async () => {
        currentCount.value = 8

        const result = await generateWeekInventory('micro-1', { force: true })

        // generateSessionPool is invoked (then short-circuits via our mock).
        expect(genPool).toHaveBeenCalledTimes(1)
        expect(result.success).toBe(false)
    })

    it('generates when the week is empty', async () => {
        currentCount.value = 0

        await generateWeekInventory('micro-1')

        expect(genPool).toHaveBeenCalledTimes(1)
    })
})
