-- =============================================================================
-- Session Inventory Architecture
-- Migration 010: Decouples training sessions from calendar weeks
--
-- This migration introduces a flexible inventory-based programming system:
-- - Sessions are generated as unscheduled inventory (week_number, no dates)
-- - Users allocate sessions to calendar dates based on their schedule
-- - Regeneration only affects inventory, not completed workouts
-- - Supports flexible start dates and rest day preferences
-- =============================================================================

-- =============================================================================
-- STEP 1: CREATE session_inventory TABLE
-- =============================================================================

CREATE TABLE public.session_inventory (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mesocycle_id UUID NOT NULL REFERENCES public.mesocycles(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Logical organization (week_number is relative to mesocycle, not calendar)
    week_number SMALLINT NOT NULL,
    session_priority SMALLINT DEFAULT 1 CHECK (session_priority BETWEEN 1 AND 3),
    -- 1 = must-do (core session)
    -- 2 = recommended (beneficial but can skip if needed)
    -- 3 = optional (bonus volume if time/energy permits)

    -- Session details
    modality TEXT NOT NULL CHECK (modality IN ('LIFTING', 'CARDIO', 'METCON', 'RUCKING', 'MOBILITY')),
    name TEXT NOT NULL,
    coach_notes TEXT,
    estimated_duration_minutes SMALLINT,
    load_budget NUMERIC(3,1),

    -- Scheduling state
    scheduled_date DATE,
    completed_at TIMESTAMPTZ,
    is_approved BOOLEAN DEFAULT false,

    -- Coaching context (carries over from previous sessions)
    carry_over_notes TEXT,
    adjustment_pending JSONB,

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE public.session_inventory IS
    'Unscheduled training sessions. Generated by AI coaches as inventory, then allocated to calendar dates by user.';

COMMENT ON COLUMN public.session_inventory.week_number IS
    'Logical week number within mesocycle (1, 2, 3...), NOT calendar week';

COMMENT ON COLUMN public.session_inventory.session_priority IS
    '1=must-do core session, 2=recommended, 3=optional bonus volume';

COMMENT ON COLUMN public.session_inventory.scheduled_date IS
    'NULL until allocated to calendar. Once set, becomes a scheduled workout.';

COMMENT ON COLUMN public.session_inventory.carry_over_notes IS
    'Coaching notes from previous session assessment (e.g., "reduce volume due to fatigue")';

COMMENT ON COLUMN public.session_inventory.adjustment_pending IS
    'Pending coach-suggested modifications: { type, reason, original, modified }';

CREATE INDEX idx_session_inventory_user ON public.session_inventory(user_id);
CREATE INDEX idx_session_inventory_mesocycle ON public.session_inventory(mesocycle_id);
CREATE INDEX idx_session_inventory_week ON public.session_inventory(user_id, mesocycle_id, week_number);
CREATE INDEX idx_session_inventory_scheduled ON public.session_inventory(user_id, scheduled_date) WHERE scheduled_date IS NOT NULL;
CREATE INDEX idx_session_inventory_unscheduled ON public.session_inventory(user_id, mesocycle_id) WHERE scheduled_date IS NULL;

-- =============================================================================
-- STEP 2: CREATE training_constraints TABLE
-- =============================================================================

CREATE TABLE public.training_constraints (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    mesocycle_id UUID NOT NULL REFERENCES public.mesocycles(id) ON DELETE CASCADE,

    -- Availability
    unavailable_days TEXT[] DEFAULT '{}',
    -- e.g., ['wednesday', 'sunday'] = cannot train these days
    preferred_start_date DATE,
    sessions_per_week SMALLINT DEFAULT 4 CHECK (sessions_per_week BETWEEN 2 AND 7),

    -- Interference preferences
    no_heavy_legs_before_run BOOLEAN DEFAULT true,
    min_rest_between_heavy_sessions_hours SMALLINT DEFAULT 48,
    prefer_am_or_pm TEXT CHECK (prefer_am_or_pm IN ('morning', 'evening', 'no_preference')),

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(user_id, mesocycle_id)
);

COMMENT ON TABLE public.training_constraints IS
    'User scheduling preferences and constraints for session allocation.';

COMMENT ON COLUMN public.training_constraints.unavailable_days IS
    'Days of week user cannot train (lowercase: monday, tuesday, etc.)';

COMMENT ON COLUMN public.training_constraints.no_heavy_legs_before_run IS
    'Avoid scheduling heavy lower body + endurance run on consecutive days';

CREATE INDEX idx_training_constraints_user ON public.training_constraints(user_id);
CREATE INDEX idx_training_constraints_mesocycle ON public.training_constraints(mesocycle_id);

-- =============================================================================
-- STEP 3: ADD COLUMNS TO EXISTING TABLES
-- =============================================================================

-- Add block_duration preference to profiles (for onboarding)
ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS preferred_block_duration SMALLINT DEFAULT 6 CHECK (preferred_block_duration IN (4, 6, 8, 12));

COMMENT ON COLUMN public.profiles.preferred_block_duration IS
    'Preferred mesocycle duration in weeks: 4 (short), 6 (standard), 8 (extended), 12 (periodized)';

-- Add session_inventory reference to workouts (for linking allocated sessions)
ALTER TABLE public.workouts
    ADD COLUMN IF NOT EXISTS session_inventory_id UUID REFERENCES public.session_inventory(id) ON DELETE SET NULL;

COMMENT ON COLUMN public.workouts.session_inventory_id IS
    'References the inventory session that was allocated to create this workout. NULL for legacy workouts.';

CREATE INDEX idx_workouts_inventory ON public.workouts(session_inventory_id);

-- =============================================================================
-- STEP 4: CREATE session_assessments TABLE (for daily coaching loop)
-- =============================================================================

CREATE TABLE public.session_assessments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    workout_id UUID NOT NULL REFERENCES public.workouts(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- User input (quick check-in after session)
    overall_feeling TEXT CHECK (overall_feeling IN ('great', 'as_expected', 'struggled', 'skipped')),
    energy_level TEXT CHECK (energy_level IN ('high', 'normal', 'low', 'very_low')),
    had_pain BOOLEAN DEFAULT false,
    pain_details TEXT,
    athlete_notes TEXT,

    -- AI-generated analysis
    performance_summary TEXT,
    -- e.g., "Hit all targets, excellent session"
    carry_over_notes TEXT,
    -- e.g., "Ready for progression next session" or "Consider reducing volume Friday"
    adjustment_recommended JSONB,
    -- { type: 'reduce_volume', magnitude: 10, reason: 'RPE 9+ on squats', target_session_id: '...' }

    -- Metadata
    assessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(workout_id)
);

COMMENT ON TABLE public.session_assessments IS
    'Post-session athlete feedback + AI coaching analysis for daily training adjustments.';

CREATE INDEX idx_session_assessments_user ON public.session_assessments(user_id);
CREATE INDEX idx_session_assessments_date ON public.session_assessments(assessed_at);

-- =============================================================================
-- STEP 5: CREATE coaching_adjustments TABLE (adjustment queue)
-- =============================================================================

CREATE TABLE public.coaching_adjustments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    session_inventory_id UUID NOT NULL REFERENCES public.session_inventory(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- What changed
    adjustment_type TEXT NOT NULL CHECK (adjustment_type IN (
        'reduce_intensity',
        'reduce_volume',
        'increase_rest',
        'swap_exercise',
        'add_deload',
        'modify_pace',
        'skip_session'
    )),
    original_prescription JSONB NOT NULL,
    modified_prescription JSONB NOT NULL,

    -- Why it changed
    reason TEXT NOT NULL,
    triggering_assessment_id UUID REFERENCES public.session_assessments(id) ON DELETE SET NULL,

    -- User interaction
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'overridden', 'expired')),
    user_response TEXT,

    -- Metadata
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);

COMMENT ON TABLE public.coaching_adjustments IS
    'Pending or resolved coach-suggested modifications to upcoming sessions based on performance data.';

CREATE INDEX idx_coaching_adjustments_user ON public.coaching_adjustments(user_id);
CREATE INDEX idx_coaching_adjustments_session ON public.coaching_adjustments(session_inventory_id);
CREATE INDEX idx_coaching_adjustments_status ON public.coaching_adjustments(user_id, status) WHERE status = 'pending';

-- =============================================================================
-- STEP 6: ADD TRIGGERS
-- =============================================================================

CREATE TRIGGER set_session_inventory_updated_at
    BEFORE UPDATE ON public.session_inventory
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

CREATE TRIGGER set_training_constraints_updated_at
    BEFORE UPDATE ON public.training_constraints
    FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

-- =============================================================================
-- STEP 7: RLS POLICIES
-- =============================================================================

-- session_inventory
ALTER TABLE public.session_inventory ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own inventory"
    ON public.session_inventory FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own inventory"
    ON public.session_inventory FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own inventory"
    ON public.session_inventory FOR UPDATE
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own inventory"
    ON public.session_inventory FOR DELETE USING (auth.uid() = user_id);

-- training_constraints
ALTER TABLE public.training_constraints ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own constraints"
    ON public.training_constraints FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own constraints"
    ON public.training_constraints FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own constraints"
    ON public.training_constraints FOR UPDATE
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own constraints"
    ON public.training_constraints FOR DELETE USING (auth.uid() = user_id);

-- session_assessments
ALTER TABLE public.session_assessments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own assessments"
    ON public.session_assessments FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own assessments"
    ON public.session_assessments FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own assessments"
    ON public.session_assessments FOR UPDATE
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own assessments"
    ON public.session_assessments FOR DELETE USING (auth.uid() = user_id);

-- coaching_adjustments
ALTER TABLE public.coaching_adjustments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own adjustments"
    ON public.coaching_adjustments FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own adjustments"
    ON public.coaching_adjustments FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own adjustments"
    ON public.coaching_adjustments FOR UPDATE
    USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own adjustments"
    ON public.coaching_adjustments FOR DELETE USING (auth.uid() = user_id);
